const STORE={users:'kleats_users',foods:'kleats_foods',orders:'kleats_orders',reviews:'kleats_reviews',categories:'kleats_categories',session:'kleats_session'};
const defaultCategories=['Indian','Pizza','Burgers','Healthy','Desserts','Beverages'];
const seedFoods=[
 {id:'f1',name:'Butter Chicken Bowl',restaurant:'Spice Route',category:'Indian',price:249,emoji:'🍛',rating:4.9,time:'25–30 min',description:'Creamy tomato gravy, tender chicken and fragrant basmati rice.',badge:'Bestseller',tone:''},
 {id:'f2',name:'Garden Pesto Pizza',restaurant:'Crust & Craft',category:'Pizza',price:399,emoji:'🍕',rating:4.8,time:'30–35 min',description:'Hand-stretched sourdough, basil pesto, vegetables and mozzarella.',badge:'Popular',tone:'green-bg'},
 {id:'f3',name:'Classic Smash Burger',restaurant:'Burger Yard',category:'Burgers',price:299,emoji:'🍔',rating:4.7,time:'20–25 min',description:'Double smashed patties, caramelised onions and house sauce.',badge:'Top rated',tone:'pink-bg'},
 {id:'f4',name:'Green Goddess Salad',restaurant:'The Fresh Fork',category:'Healthy',price:219,emoji:'🥗',rating:4.6,time:'15–20 min',description:'Crisp greens, avocado, seeds and a lemon herb dressing.',badge:'Fresh pick',tone:'green-bg'},
 {id:'f5',name:'Truffle Mushroom Pasta',restaurant:'Olive Table',category:'Italian',price:349,emoji:'🍝',rating:4.8,time:'25–30 min',description:'Silky cream sauce, roasted mushrooms and parmesan.',badge:'Chef special',tone:'purple-bg'},
 {id:'f6',name:'Mango Cheesecake',restaurant:'Sugar Cloud',category:'Desserts',price:179,emoji:'🍰',rating:4.9,time:'15–20 min',description:'Silky cheesecake topped with bright Alphonso mango.',badge:'Sweet pick',tone:'pink-bg'},
 {id:'f7',name:'Masala Chai',restaurant:'Chai Chapter',category:'Beverages',price:89,emoji:'☕',rating:4.7,time:'10–15 min',description:'Slow-brewed tea with cardamom, ginger and warm spices.',badge:'Comfort sip',tone:''},
 {id:'f8',name:'Paneer Tikka Wrap',restaurant:'Spice Route',category:'Indian',price:199,emoji:'🌯',rating:4.8,time:'20–25 min',description:'Charred paneer, crunchy salad and mint chutney in a soft wrap.',badge:'Veg favourite',tone:'green-bg'}
];
function read(key,fallback=[]){try{return JSON.parse(localStorage.getItem(key))??fallback}catch{return fallback}}
function write(key,value){localStorage.setItem(key,JSON.stringify(value))}
function initStore(){if(!localStorage.getItem(STORE.users))write(STORE.users,[{name:'Administrator',email:'admin@kleats.com',password:'admin123',mobile:'9999999999',role:'admin'}]);if(!localStorage.getItem(STORE.foods))write(STORE.foods,seedFoods);if(!localStorage.getItem(STORE.categories))write(STORE.categories,defaultCategories);if(!localStorage.getItem(STORE.orders))write(STORE.orders,[]);if(!localStorage.getItem(STORE.reviews))write(STORE.reviews,[])}
function foods(){return read(STORE.foods,seedFoods)}
function users(){return read(STORE.users,[])}
function session(){return localStorage.getItem(STORE.session)}
function currentUser(){const email=session();return users().find(u=>u.email===email)||null}
function money(value){return '₹'+Number(value).toLocaleString('en-IN')}
function esc(value){return String(value??'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]))}
function toast(message,type='success'){let el=document.getElementById('toast');if(!el){el=document.createElement('div');el.id='toast';document.body.appendChild(el)}el.className='toast '+type;el.textContent=message;setTimeout(()=>el.className='toast hide',2600)}
function requireLogin(){if(!currentUser()){toast('Please log in to continue.','error');setTimeout(()=>location.href='login.html',600);return false}return true}
function renderHeader(){const host=document.getElementById('siteHeader');if(!host)return;const user=currentUser();const page=document.body.dataset.page||'';host.innerHTML=`<header class="site-header"><div class="container nav"><a class="brand" href="index.html"><span class="brand-mark">✦</span><span>KL <em>Eats</em></span></a><nav class="main-nav"><a class="${page==='home'?'active':''}" href="index.html">Home</a><a class="${page==='menu'?'active':''}" href="menu.html">Browse menu</a>${user?.role==='admin'?'<a href="admin.html">Admin</a>':''}<a class="${page==='orders'?'active':''}" href="orders.html">My orders</a></nav><div class="header-actions"><a class="cart-link" href="cart.html">Cart <span class="cart-count">${cartCount()}</span></a>${user?`<span class="user-pill">Hi, ${esc(user.name.split(' ')[0])}</span><button class="btn btn-small btn-light" data-action="logout">Logout</button>`:'<a class="btn btn-small btn-primary" href="login.html">Login</a>'}</div><button class="mobile-menu" aria-label="Menu">☰</button></div></header>`}
function cartKey(){return session()?`kleats_cart_${session()}`:'kleats_guest_cart'}
function getCart(){return read(cartKey(),[])}
function saveCart(cart){write(cartKey(),cart);renderHeader()}
function cartCount(){return getCart().reduce((sum,item)=>sum+item.qty,0)}
function addToCart(id){if(!requireLogin())return;const item=foods().find(f=>f.id===id);if(!item)return;const cart=getCart();const found=cart.find(i=>i.id===id);if(found)found.qty++;else cart.push({id,qty:1});saveCart(cart);toast(`${item.name} added to cart`);renderCurrentPage()}
function updateQty(id,delta){const cart=getCart();const item=cart.find(i=>i.id===id);if(!item)return;item.qty+=delta;saveCart(item.qty<1?cart.filter(i=>i.id!==id):cart);renderCart()}
function foodCard(food){return `<article class="food-card"><div class="food-image ${food.tone||''}"><span class="food-badge">${esc(food.badge||food.category)}</span><span>${food.emoji}</span></div><div class="food-info"><h3>${esc(food.name)}</h3><div class="food-meta">${esc(food.restaurant)} · ★ ${food.rating} · ${food.time}</div><p class="food-meta">${esc(food.description)}</p><div class="food-bottom"><span class="food-price">${money(food.price)}</span><button class="add-btn" data-add="${food.id}">+ Add</button></div></div></article>`}
function renderFoodGrid(target,items=foods()){const el=document.getElementById(target);if(el)el.innerHTML=items.length?items.map(foodCard).join(''):'<div class="empty-state">No meals match your search.</div>'}
function renderFeatured(){renderFoodGrid('featuredFood',foods().slice(0,4))}
function renderMenu(){let list=foods();const params=new URLSearchParams(location.search);const initial=params.get('category');const search=document.getElementById('menuSearch');const filter=document.getElementById('categoryFilter');if(filter){filter.innerHTML='<option value="all">All categories</option>'+[...new Set(foods().map(f=>f.category))].sort().map(c=>`<option>${esc(c)}</option>`).join('');if(initial)filter.value=initial}const apply=()=>{const q=(search?.value||'').toLowerCase();const cat=filter?.value||'all';list=foods().filter(f=>(cat==='all'||f.category===cat)&&(!q||`${f.name} ${f.restaurant} ${f.category}`.toLowerCase().includes(q)));renderFoodGrid('menuGrid',list)};search?.addEventListener('input',apply);filter?.addEventListener('change',apply);apply()}
function renderDashboard(){const user=currentUser();if(!user){location.href='login.html';return}const welcome=document.getElementById('welcomeName');if(welcome)welcome.textContent=user.name.split(' ')[0];renderFoodGrid('dashboardFood',foods().slice(0,4));const mine=read(STORE.orders,[]).filter(o=>o.email===user.email).sort((a,b)=>b.createdAt-a.createdAt);const list=document.getElementById('recentOrders');if(list)list.innerHTML=mine.length?mine.slice(0,3).map(orderRow).join(''):'<div class="empty-state">Your order history will appear here.<br><a class="text-link" href="menu.html">Start browsing →</a></div>';const count=document.getElementById('orderCount');if(count)count.textContent=mine.length}
function orderRow(order){return `<div class="order-row"><div><strong>${esc(order.id)}</strong><br><small>${order.items.reduce((s,i)=>s+i.qty,0)} item(s) · ${money(order.total)}</small></div><span class="status ${order.status.toLowerCase().replace(' ','-')}">${esc(order.status)}</span></div>`}
function renderCart(){const area=document.getElementById('cartItems');if(!area)return;const all=foods();const cart=getCart();if(!cart.length){area.innerHTML='<div class="empty-state"><div style="font-size:44px">🛒</div><h3>Your cart is empty</h3><p>Add something delicious to get started.</p><a class="btn btn-primary" style="margin-top:15px" href="menu.html">Browse menu</a></div>';const sum=document.getElementById('cartSummary');if(sum)sum.innerHTML='';return}const detailed=cart.map(i=>({...all.find(f=>f.id===i.id),qty:i.qty})).filter(i=>i.name);area.innerHTML=detailed.map(i=>`<div class="cart-item"><div class="cart-emoji">${i.emoji}</div><div class="cart-item-info"><strong>${esc(i.name)}</strong><small>${esc(i.restaurant)} · ${money(i.price)} each</small></div><div class="qty-control"><button data-qty="${i.id}" data-delta="-1">−</button><strong>${i.qty}</strong><button data-qty="${i.id}" data-delta="1">+</button></div><strong>${money(i.price*i.qty)}</strong></div>`).join('');const subtotal=detailed.reduce((s,i)=>s+i.price*i.qty,0);const delivery=subtotal>=499?0:39;const total=subtotal+delivery;document.getElementById('cartSummary').innerHTML=`<h2>Order summary</h2><div class="summary-line"><span>Subtotal</span><strong>${money(subtotal)}</strong></div><div class="summary-line"><span>Delivery fee</span><strong>${delivery?money(delivery):'Free'}</strong></div><div class="summary-line summary-total"><span>Total</span><strong>${money(total)}</strong></div><form id="checkoutForm" class="checkout-form"><div class="field"><label for="address">Delivery address</label><textarea id="address" required placeholder="House number, street, city"></textarea></div><div class="field"><label for="payment">Payment method</label><select id="payment"><option>Cash on Delivery</option><option>UPI (demo)</option><option>Card (demo)</option></select></div><button class="btn btn-primary" type="submit">Place order · ${money(total)}</button></form>`;document.getElementById('checkoutForm').addEventListener('submit',e=>placeOrder(e,total,delivery))}
function placeOrder(event,total,delivery){event.preventDefault();if(!requireLogin())return;const address=document.getElementById('address').value.trim();if(!address)return;const all=foods();const items=getCart().map(i=>{const f=all.find(x=>x.id===i.id);return {id:f.id,name:f.name,emoji:f.emoji,price:f.price,qty:i.qty}});const order={id:'KL'+Date.now().toString().slice(-7),email:session(),customer:currentUser().name,items,address,payment:document.getElementById('payment').value,subtotal:total-delivery,delivery,total,status:'Placed',createdAt:Date.now(),review:null};const orders=read(STORE.orders,[]);orders.push(order);write(STORE.orders,orders);saveCart([]);toast('Order placed successfully!');setTimeout(()=>location.href='orders.html',650)}
function timeline(status){const steps=['Placed','Preparing','Out for delivery','Delivered'];const current=steps.indexOf(status);return `<div class="timeline">${steps.map((s,i)=>`<div class="timeline-step ${i<=current?'active':''}"><div class="timeline-dot">${i<=current?'✓':''}</div>${s}</div>`).join('')}</div>`}
function renderOrders(){const user=currentUser();if(!user){location.href='login.html';return}const list=document.getElementById('ordersList');const orders=read(STORE.orders,[]).filter(o=>o.email===user.email).sort((a,b)=>b.createdAt-a.createdAt);if(!orders.length){list.innerHTML='<div class="empty-state"><div style="font-size:44px">🍽️</div><h3>No orders yet</h3><p>Place your first order and track it here.</p><a class="btn btn-primary" style="margin-top:15px" href="menu.html">Explore menu</a></div>';return}list.innerHTML=orders.map(o=>`<article class="panel" style="margin-bottom:18px"><div class="panel-heading"><div><h2>${esc(o.id)}</h2><small class="food-meta">${new Date(o.createdAt).toLocaleString('en-IN')} · ${esc(o.payment)}</small></div><span class="status ${o.status.toLowerCase().replace(' ','-')}">${esc(o.status)}</span></div><div class="food-meta">Delivering to: ${esc(o.address)}</div>${timeline(o.status)}<div class="order-items">${o.items.map(i=>`<div class="order-row"><span>${i.emoji} ${esc(i.name)} × ${i.qty}</span><strong>${money(i.price*i.qty)}</strong></div>`).join('')}</div><div class="summary-line summary-total"><span>Total</span><strong>${money(o.total)}</strong></div>${o.status==='Delivered'&&!o.review?`<div class="review-box"><strong>How was your meal?</strong><form data-review-form="${o.id}"><div class="field" style="margin-top:8px"><select name="rating"><option value="5">★★★★★ Excellent</option><option value="4">★★★★ Great</option><option value="3">★★★ Good</option><option value="2">★★ Needs improvement</option><option value="1">★ Poor</option></select></div><textarea name="comment" placeholder="Share a quick review"></textarea><button class="btn btn-small btn-primary" type="submit">Submit review</button></form></div>`:o.review?`<div class="review-box"><strong>Your review</strong><div class="rating">${'★'.repeat(o.review.rating)}${'☆'.repeat(5-o.review.rating)}</div><small>${esc(o.review.comment||'Thanks for your feedback!')}</small></div>`:''}</article>`).join('')}
function submitReview(form){const id=form.dataset.reviewForm;const orders=read(STORE.orders,[]);const order=orders.find(o=>o.id===id);if(!order)return;const data=new FormData(form);order.review={rating:Number(data.get('rating')),comment:data.get('comment')};write(STORE.orders,orders);const reviews=read(STORE.reviews,[]);reviews.push({orderId:id,email:session(),rating:order.review.rating,comment:order.review.comment,createdAt:Date.now()});write(STORE.reviews,reviews);toast('Thanks for your review!');renderOrders()}
function renderAdmin(){if(currentUser()?.role!=='admin'){location.href='login.html';return}const allOrders=read(STORE.orders,[]);document.getElementById('adminFoodCount').textContent=foods().length;document.getElementById('adminOrderCount').textContent=allOrders.length;document.getElementById('adminCustomerCount').textContent=users().filter(u=>u.role!=='admin').length;document.getElementById('adminRevenue').textContent=money(allOrders.reduce((s,o)=>s+o.total,0));renderAdminFood();renderAdminOrders();renderAdminUsers();renderCategories()}
function renderAdminFood(){const table=document.getElementById('foodTable');if(!table)return;table.innerHTML=foods().map(f=>`<tr><td>${f.emoji} ${esc(f.name)}</td><td>${esc(f.restaurant)}</td><td><span class="tag">${esc(f.category)}</span></td><td>${money(f.price)}</td><td><button class="btn btn-small btn-light" data-edit-food="${f.id}">Edit</button> <button class="btn btn-small btn-danger" data-delete-food="${f.id}">Delete</button></td></tr>`).join('')}
function renderAdminOrders(){const table=document.getElementById('adminOrderTable');if(!table)return;const orders=read(STORE.orders,[]).sort((a,b)=>b.createdAt-a.createdAt);table.innerHTML=orders.length?orders.map(o=>`<tr><td>${esc(o.id)}</td><td>${esc(o.customer)}<br><small>${esc(o.email)}</small></td><td>${o.items.map(i=>`${i.emoji} ${i.qty}`).join(' ')}</td><td>${money(o.total)}</td><td><select data-order-status="${o.id}">${['Placed','Preparing','Out for delivery','Delivered','Cancelled'].map(s=>`<option ${s===o.status?'selected':''}>${s}</option>`).join('')}</select></td></tr>`).join(''):'<tr><td colspan="5">No orders yet.</td></tr>'}
function renderAdminUsers(){const table=document.getElementById('userTable');if(!table)return;table.innerHTML=users().filter(u=>u.role!=='admin').map(u=>`<tr><td>${esc(u.name)}</td><td>${esc(u.email)}</td><td>${esc(u.mobile||'—')}</td><td>${read(STORE.orders,[]).filter(o=>o.email===u.email).length}</td></tr>`).join('')||'<tr><td colspan="4">No registered customers yet.</td></tr>'}
function renderCategories(){const el=document.getElementById('categoryManager');if(!el)return;el.innerHTML=read(STORE.categories,defaultCategories).map(c=>`<span class="tag">${esc(c)} <button data-delete-category="${esc(c)}">×</button></span>`).join('')}
function fillFoodForm(food){document.getElementById('foodId').value=food?.id||'';document.getElementById('foodName').value=food?.name||'';document.getElementById('foodRestaurant').value=food?.restaurant||'';document.getElementById('foodCategory').value=food?.category||'Indian';document.getElementById('foodPrice').value=food?.price||'';document.getElementById('foodEmoji').value=food?.emoji||'🍽️';document.getElementById('foodDescription').value=food?.description||'';document.getElementById('foodFormTitle').textContent=food?'Edit food item':'Add food item';document.getElementById('cancelEdit').style.display=food?'inline-flex':'none';window.scrollTo({top:0,behavior:'smooth'})}
function saveFood(e){e.preventDefault();const id=document.getElementById('foodId').value;const item={id:id||'f'+Date.now(),name:document.getElementById('foodName').value.trim(),restaurant:document.getElementById('foodRestaurant').value.trim(),category:document.getElementById('foodCategory').value,price:Number(document.getElementById('foodPrice').value),emoji:document.getElementById('foodEmoji').value||'🍽️',description:document.getElementById('foodDescription').value.trim(),rating:4.7,time:'20–30 min',badge:'New pick',tone:''};if(!item.name||!item.restaurant||!item.price)return;const list=foods();const index=list.findIndex(f=>f.id===id);if(index>-1)list[index]=item;else list.push(item);write(STORE.foods,list);toast(id?'Food item updated':'Food item added');fillFoodForm();renderAdmin()}
function renderCurrentPage(){const page=document.body.dataset.page;if(page==='home')renderFeatured();if(page==='menu')renderMenu();if(page==='dashboard')renderDashboard();if(page==='cart')renderCart();if(page==='orders')renderOrders();if(page==='admin')renderAdmin()}
function setupAuth(){const register=document.getElementById('registerForm');register?.addEventListener('submit',e=>{e.preventDefault();const name=document.getElementById('name').value.trim(),email=document.getElementById('email').value.trim().toLowerCase(),password=document.getElementById('password').value,mobile=document.getElementById('mobile').value.trim(),msg=document.getElementById('formMessage');if(password.length<6){msg.textContent='Password must be at least 6 characters.';msg.className='form-message error';return}const list=users();if(list.some(u=>u.email===email)){msg.textContent='An account with this email already exists.';msg.className='form-message error';return}list.push({name,email,password,mobile,role:'user'});write(STORE.users,list);msg.textContent='Account created. Redirecting to login…';msg.className='form-message success';setTimeout(()=>location.href='login.html',800)});const login=document.getElementById('loginForm');login?.addEventListener('submit',e=>{e.preventDefault();const email=document.getElementById('loginEmail').value.trim().toLowerCase(),password=document.getElementById('loginPassword').value,msg=document.getElementById('formMessage');const user=users().find(u=>u.email===email&&u.password===password);if(!user){msg.textContent='Invalid email or password. Try registering first.';msg.className='form-message error';return}localStorage.setItem(STORE.session,user.email);location.href=user.role==='admin'?'admin.html':'user.html'})}
function bindGlobal(){document.addEventListener('click',e=>{const add=e.target.closest('[data-add]');if(add)addToCart(add.dataset.add);const qty=e.target.closest('[data-qty]');if(qty)updateQty(qty.dataset.qty,Number(qty.dataset.delta));const logout=e.target.closest('[data-action="logout"]');if(logout){localStorage.removeItem(STORE.session);location.href='index.html'}});document.addEventListener('submit',e=>{if(e.target.matches('[data-review-form]')){e.preventDefault();submitReview(e.target)}})}
function setupAdmin(){document.getElementById('foodForm')?.addEventListener('submit',saveFood);document.getElementById('cancelEdit')?.addEventListener('click',()=>fillFoodForm());document.getElementById('categoryForm')?.addEventListener('submit',e=>{e.preventDefault();const input=document.getElementById('newCategory'),value=input.value.trim();if(!value)return;const cats=read(STORE.categories,defaultCategories);if(!cats.includes(value))cats.push(value);write(STORE.categories,cats);input.value='';renderCategories();toast('Category added')});document.addEventListener('click',e=>{const edit=e.target.closest('[data-edit-food]');if(edit)fillFoodForm(foods().find(f=>f.id===edit.dataset.editFood));const del=e.target.closest('[data-delete-food]');if(del&&confirm('Delete this food item?')){write(STORE.foods,foods().filter(f=>f.id!==del.dataset.deleteFood));renderAdmin()};const cat=e.target.closest('[data-delete-category]');if(cat){write(STORE.categories,read(STORE.categories,defaultCategories).filter(c=>c!==cat.dataset.deleteCategory));renderCategories()}});document.addEventListener('change',e=>{const select=e.target.closest('[data-order-status]');if(select){const orders=read(STORE.orders,[]),order=orders.find(o=>o.id===select.dataset.orderStatus);if(order){order.status=select.value;write(STORE.orders,orders);toast('Order status updated')}}})}
initStore();renderHeader();bindGlobal();setupAuth();setupAdmin();renderCurrentPage();
